### ISSUE TITLE
Out of bounds memory write in I2C Handler

### ISSUE THREAD

**Issue by jeremyncc** [opencomputeproject/OCP-OSF-Tektagon_Community_Edition#2]
A physical attacker can tamper with the I2C bus in order to inject `UfmWriteFIFO` commands. If more than 64 such commands are injected, `gFifoData` will be incremented beyond the end of the `gUfmFifoData[]` array, resulting in out-of-bounds memory writes on the lines shown below:

https://github.com/opencomputeproject/Tektagon-OpenEdition/blob/f7350a3a175373532f2ecafc82745a827397d4a8/zephyr/ApplicationLayer/tektagon/src/Smbus_mailbox/Smbus_mailbox.c#L1225-L1227

Before writing to `gUfmFifoData[]`, the index `gFifoData` should be checked to ensure it is less than `sizeof(gUfmFifoData)`.

It appears that a similar vulnerability can occur if repeated `UfmReadFIFO` commands are sent, however, this would result in out-of-bounds memory reads instead of writes.

**Comment by presannar** [comment]
Tx jermeyncc, looking into this issue. will update with a fix.

**Comment by jeremyncc** [comment]
any update on this?

**Comment by vigneshs88** [comment]
Hi Jeremy Boone,

We are working on this. We will close this issue by End of Jan 2023.

Regards,
Vignesh

**Comment by vigneshs88** [comment]
Hi Jeremy Boone, Next release is planned in end of Feb/early March. These fixes will be part of the release.

**Comment by jeremyncc** [comment]
Hi @vigneshs88, I took a look at the recent commit (https://github.com/opencomputeproject/Tektagon-OpenEdition/commit/d6d935ecb76ac0e2e5715874b12ed832dae998f2). It looks like this reported memory corruption issue has been fixed by checking the lengths before writing to the array, as shown below:

https://github.com/opencomputeproject/Tektagon-OpenEdition/blob/d6d935ecb76ac0e2e5715874b12ed832dae998f2/oe-src/ApplicationLayer/tektagon/src/Smbus_mailbox/Smbus_mailbox.c#L1230-L1241

I'll close this issue now. Thanks!
