### ISSUE TITLE
How to Build Tektagon CE on Windows environment

### ISSUE THREAD

**Issue by tyagi3** [opencomputeproject/OCP-OSF-Tektagon_Community_Edition#6]
In readme.md, it explains that how to build Tektagon CE on Linux environment only. 
Could you tell us setup and build Tektagon CE on Windows?
And could you create build.bat?

**Comment by presannar** [comment]
@tyagi3,
We have looked into the request and added the windows build support script. Also updated is the Readme instructions for setting up the windows build.

With Regards,

**Comment by tyagi3** [comment]
@presannar 
Thank you for your kindly support. I will try the procedure.

Best Regards,
